### PR TITLE
Added blocks to Snake game

### PR DESCRIPTION
**Pull request by silversword05**
Sir, I have made the changes ordered by you

### CODE REVIEW

**Comment by silversword05** [comment]
Sir, I have made repetitive commits by mistake. Please pardon me. I will not repeat it again. The Snake.py file contains the required changes.

**Comment by jajodiaraghav** [comment]
I think you either did not understand what I mentioned in the previous PR, or you didn't bother to understand it.

capture

Have a look at your commit messages. Do you think any org will merge your PR with such commit messages? "Sir make changes"? "Sir I have made the changes as you told"? Really?

Open Source is more about learning and developing your skills rather than getting your PRs merged. Learn to use git properly, learn to write proper commit messages, learn to open and claim issues before creating PRs.

> Sir, I have made the changes ordered by you

ordered => requested

**Comment by jajodiaraghav** [comment]
These links might help:
https://git-scm.com/book/en/v2/Git-Basics-Undoing-Things
https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History
https://github.com/zulip/zulip-gci/blob/master/docs/fixing-commits.md

**Comment by silversword05** [comment]
I will take care of it next time

**Pull request merged**
