### PR TITLE
rectified the speed issue #21

### PR DESCRIPTION
**Pull request by vinaykrishna64**
The Boolean speed_boost of 5 is moving the head ahead of the objects that has been rectified using a for loop which  changes the position multiple times.

### CODE REVIEW

**Comment by vinaykrishna64** [comment]
I have rectified the speed issue and created a class for worlds so that a new world is generated after every five points scored

**Comment by jajodiaraghav** [comment]
@vinaykrishna64 This looks really awesome. Great job!

There are a few issues which I want you to fix as I am getting an error when I run the app:
1. Change class in 'worlds.py' file to a function, Remove `def get():` and simply change `class worlds` to `def worlds(n):`

Advice:
1. You have created this PR from your master branch which is wrong. Please learn to use git properly. Read through online tuts.
2. Every new feature should be put in a separate PR of a separate branch. Go through the lisks I sent on gitter to use git properly. You are pushing all your commits to the same PR which is wrong.

**Comment by jajodiaraghav** [comment]
This is not what I wanted. All you had to do was convert `class worlds` to `def worlds(n):`
Why did you pasted the code in the same file

**Comment by vinaykrishna64** [comment]
Okay I've changed it

**Pull request closed without merging**
