### PR TITLE
Snakes without keyboard

### PR DESCRIPTION
**Pull request by silversword05**
I can't resolve the conflict

### CODE REVIEW

**Comment by jajodiaraghav** [comment]
Did you go through the links I sent you?
As I said earlier, You could never be a good contributor if you cannot use git, no matter how good are your coding skills.

**Review by vinaykrishna64 — COMMENTED** [review]
@AadiCool the master branch has been updated please check

**Comment by silversword05** [comment]
Sir, I have resolved the conflicts. Please check.

**Comment by jajodiaraghav** [comment]
If I merge this PR, then the user will be forced to use a mouse to play the game, and the user who prefers a keyboard won't be able to play. Am I right?

**Comment by silversword05** [comment]
never.Even you can use mouse and keyboard simultaneously.

**Comment by jajodiaraghav** [comment]
Thanks for the good work!

Some Advice:
1. https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History
2. Learn to use amend
3. I saw the button list function has been added in this PR. But this PR should only be related to mouse feature. Always create separate PRs for every issue.

**Pull request merged**
